### ISSUE TITLE
The build failed - Ultimate Guitar changes their website

### ISSUE THREAD

**Issue by masterT** [masterT/ultimate-guitar-scraper#24]
[Travis CI Logs](https://travis-ci.org/masterT/ultimate-guitar-scraper/jobs/337310112).
I'll patch it as soon as I can!

**Comment by KerryRitter** [comment]
Thanks for keeping up on this :)

**Comment by masterT** [comment]
Fixed in version `ultimate-guitar-scraper@1.0.0` 🎉
