### ISSUE TITLE
CORS error in search request

### ISSUE THREAD

**Issue by zwenza** [masterT/ultimate-guitar-scraper#31]
Hi!

First of all thanks for writing this little scraper, this is exactly what I currently need!
Unfortunately I get a CORS error when using the search function. 

The autocomplete function works fine!

Do you have any idea how to fix this, or what I am doing wrong?

**Comment by masterT** [comment]
Hi, thanks! 

First time I heard about this error, do you use this package from a server? or un the browser? Because it's meant to be used from a server.

**Comment by McCrearyD** [comment]
cors is an error when you try to make an http(s) query from a non-registered source (i.e your browser). try using node.js
