### ISSUE TITLE
Get capo, tuning, and key 

### ISSUE THREAD

**Issue by hougrammer** [masterT/ultimate-guitar-scraper#32]
Thanks for writing this scraper!  I think it would be nice to get the capo, tuning, and key from the tab meta data.  I looked in the JSON response and noticed these are easily accessible.

**Comment by masterT** [comment]
Thanks! I would be a great idea!

**Comment by masterT** [comment]
Done and available in `ultimate-guitar-scraper@1.1.0` 🎉 Thank you again @hougrammer !
