### ISSUE TITLE
Installation fails:  "dependency of itself"

### ISSUE THREAD

**Issue by mikegilchrist** [masterT/ultimate-guitar-scraper#4]
I get the following error when trying to install the package following the instructions in the README file
(NB:log file attached)

[cheoah ~/Repositories/ultimate-guitar-scraper]$ npm install ultimate-guitar-scraper
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "ultimate-guitar-scraper"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install ultimate-guitar-scraper as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mikeg/Repositories/ultimate-guitar-scraper/npm-debug.log

[npm-debug.log.txt](https://github.com/masterT/ultimate-guitar-scraper/files/514189/npm-debug.log.txt)

**Comment by masterT** [comment]
I was able to reproduce the error (node v4.2.6 and npm v3.5.2). It happened because you are trying to install the module with in the module. 

If you want to use `ultimate-guitar-scraper` in your project:

```bash
cd your/projet/path
npm install ultimate-guitar-scraper --save
```

If you want to install the `ultimate-guitar-scraper` dependencies:

```bash
git clone https://github.com/masterT/ultimate-guitar-scraper
cd ultimate-guitar-scraper
npm install
# ready to rock! 🎸
# run the examples
node examples/basic.js
# run the test
npm test
```
I there is any problem don't hesitate! 😊

**Comment by masterT** [comment]
By curiosity, want do you want to do with the module?
- Add a new feature?
- Fix a bug? 
- Fork your one version?
- Other?

I am asking because I planned to publish a new version soon (see [branch develop](https://github.com/masterT/ultimate-guitar-scraper/tree/develop)). I must first refactor the develop branch a little bite, so the code might change a lot.

**Comment by mikegilchrist** [comment]
Ha!  I don't really know what I'm doing.  I've never use these modules before 
so I'm trying to figure out how to use it.  I'd like to be able to get files 
from ultimate-guitar.com from the commandline and then prcess them locally so 
that I remove the header garbage and format them more readily for printing.

Mike

-----------------------------------------------------
Dept. of Ecology & Evolutionary Biology
Office Location: 439 Hesler Biology Building
Mailing Address: 569 Dabney Hall
		 University of Tennessee
		 Knoxville, TN 37996-1610
Web page: 	 http://eeb.bio.utk.edu/peopletwo/michael-gilchrist/
Calendar:	 http://www.tiem.utk.edu/~mikeg/calendar.html
-----------------------------------------------------

**Comment by masterT** [comment]
Nice! In the [develop branch](https://github.com/masterT/ultimate-guitar-scraper/tree/develop) you can search and fetch TAB (and more). But as I said, I will refactor the code on the branch develop. I plan to do it this month, so the code might change a lot.

Mean while if you really want to fetch TAB, you can install the module and specify the branch `develop`.

```bash
npm install github:mastert/ultimate-guitar-scraper#develop --save
```

For more info about the `npm install` try:

```bash
npm help install
```

I great place to start with node module is with the [npm tutorials](https://www.npmjs.com/package/npm_tutorial/tutorial).
